
MODEL_CONFIGS = {
    "TFVideoMAE_S_16x224_FT": {
        "img_size": 224,
        "patch_size": 16,
        "embed_dim": 384,
        "depth": 12,
        "num_heads": 6,
        "mlp_ratio": 4,
        "qkv_bias": True,
        "drop_path_rate": 0.1,
        "num_classes": 400,
    },

    "TFVideoMAE_B_16x224_FT": {
        "img_size": 224,
        "patch_size": 16,
        "embed_dim": 768,
        "depth": 12,
        "num_heads": 12,
        "mlp_ratio": 4,
        "qkv_bias": True,
        "drop_path_rate": 0.1,
        "num_classes": 400,
    },

    "TFVideoMAE_B_16x384_FT": {
        "img_size": 384,
        "patch_size": 16,
        "embed_dim": 768,
        "depth": 12,
        "num_heads": 12,
        "mlp_ratio": 4,
        "qkv_bias": True,
        "drop_path_rate": 0.1,
        "num_classes": 400,
    },

    "TFVideoMAE_L_16x224_FT": {
        "img_size": 224,
        "patch_size": 16,
        "embed_dim": 1024,
        "depth": 24,
        "num_heads": 16,
        "mlp_ratio": 4,
        "qkv_bias": True,
        "drop_path_rate": 0.1,
        "num_classes": 400,
    },

    "TFVideoMAE_L_16x384_FT": {
        "img_size": 384,
        "patch_size": 16,
        "embed_dim": 1024,
        "depth": 24,
        "num_heads": 16,
        "mlp_ratio": 4,
        "qkv_bias": True,
        "drop_path_rate": 0.1,
        "num_classes": 400,
    },

    "TFVideoMAE_L_16x512_FT": {
        "img_size": 512,
        "patch_size": 16,
        "embed_dim": 1024,
        "depth": 24,
        "num_heads": 16,
        "mlp_ratio": 4,
        "qkv_bias": True,
        "drop_path_rate": 0.1,
        "num_classes": 400,
    },

    "TFVideoMAE_H_16x224_FT": {
        "img_size": 224,
        "patch_size": 16,
        "embed_dim": 1280,
        "depth": 32,
        "num_heads": 16,
        "mlp_ratio": 4,
        "qkv_bias": True,
        "drop_path_rate": 0.1,
        "num_classes": 400,
    },

    "TFVideoMAE_S_16x224_PT": {
        "img_size":224,
        "patch_size": 16,
        "encoder_embed_dim":384,
        "encoder_depth":12,
        "encoder_num_heads":6,
        "encoder_num_classes":0,
        "decoder_num_classes":1536, 
        "decoder_embed_dim":192, 
        "decoder_num_heads":3,
        "decoder_depth":4,
        "mlp_ratio":4,
        "qkv_bias":True,
    },

    "TFVideoMAE_B_16x224_PT": {
        "img_size":224,
        "patch_size": 16,
        "encoder_embed_dim":768,
        "encoder_depth":12,
        "encoder_num_heads":12,
        "encoder_num_classes":0,
        "decoder_num_classes":1536, 
        "decoder_embed_dim":384, 
        "decoder_num_heads":6,
        "decoder_depth":4,
        "mlp_ratio":4,
        "qkv_bias":True,
    },

    "TFVideoMAE_L_16x224_PT": {
        "img_size":224,
        "patch_size": 16,
        "encoder_embed_dim":1024,
        "encoder_depth":24,
        "encoder_num_heads":16,
        "encoder_num_classes":0,
        "decoder_num_classes":1536, 
        "decoder_embed_dim":512, 
        "decoder_num_heads":8,
        "decoder_depth":12,
        "mlp_ratio":4,
        "qkv_bias":True,
    },

    "TFVideoMAE_H_16x224_PT": {
        "img_size":224,
        "patch_size": 16,
        "encoder_embed_dim":1280,
        "encoder_depth":32,
        "encoder_num_heads":16,
        "encoder_num_classes":0,
        "decoder_num_classes":1536, 
        "decoder_embed_dim":640, 
        "decoder_num_heads":8,
        "decoder_depth":12,
        "mlp_ratio":4,
        "qkv_bias":True,
    },

}